# backend/graph/state.py
from typing import TypedDict, Annotated, Literal
from datetime import datetime
import operator

class KinnectState(TypedDict):
    """
    The unified state object that flows through all agents in the LangGraph workflow.
    This is what makes the system truly agentic - every agent reads from and writes to
    this shared context, allowing autonomous decision-making without hardcoded paths.
    """
    
    # ==================== USER CONTEXT ====================
    user_id: str  # Unique patient identifier
    session_id: str  # Unique ID for this specific call
    timestamp: datetime  # When the call was initiated
    
    # ==================== CONVERSATION DATA ====================
    # We use Annotated with operator.add to append messages instead of replacing
    messages: Annotated[list[dict], operator.add]  # LangChain message format
    transcript: str  # Full text conversation after call ends
    audio_chunks: list[bytes]  # Raw audio data (for future processing)
    
    # ==================== MEMORY CONTEXT (RAG) ====================
    retrieved_memories: list[dict]  # Memories fetched from ChromaDB before call
    new_entities: list[dict]  # New facts extracted during/after call
    context_summary: str  # Human-readable summary generated by Context Agent
    
    # ==================== DIAGNOSTIC FLAGS ====================
    cognitive_score: float  # 0-100 scale, calculated by Diagnostic Agent
    anomalies_detected: list[str]  # e.g., ["forgot_medication", "repeated_question_3x"]
    needs_alert: bool  # Boolean flag that determines if Alert Agent should run
    diagnostic_report: dict  # Full structured output from Diagnostic Agent
    
    # ==================== AGENT ROUTING CONTROL ====================
    # This is the KEY to non-hardcoded flow. Agents update this field to control
    # which node executes next. The LangGraph conditional edges read this value.
    next_agent: Literal[
        "context_loader",
        "conversational_agent",
        "memory_extractor",
        "diagnostic_analyzer",
        "alert_handler",
        "END"
    ]
    
    # ==================== METADATA & ERROR HANDLING ====================
    errors: Annotated[list[str], operator.add]  # Accumulated errors during execution
    agent_outputs: dict  # Stores raw outputs from each agent for debugging